def exception():
    return None


def exception():
    return None